name: Update Website Panji.me

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
      - name: Deploy to VPS
        run: |
          ssh pxnji@5.161.53.191
          sudo cd /www/wwwroot/panji.me
          sudo git clone https://github.com/pxnji/panji.me.git
          sudo cp -r /www/wwwroot/panji.me/panji.me/* .
          sudo rm -rf /www/wwwroot/panji.me/panji.me
          exit
          EOF
