name: Update Website Panji.me

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
      - name: Deploy to VPS
        run: |
          # Replace the following placeholders with your actual deployment steps
          # For example, you might use SCP or SFTP to transfer your HTML files to the VPS
          
          # Example using SFTP
          ssh pxnji@pxnji@5.161.53.191:/www/wwwroot/panji.me <<EOF
          git clone https://github.com/pxnji/panji.me.git
          cp -r /www/wwwroot/panji.me/panji.me/* .
          rm -rf /www/wwwroot/panji.me/panji.me
          exit
          EOF
